### ISSUE TITLE
Editor unknown

### ISSUE THREAD

**Issue by thespy7** [midbel/subnet#1]
Hiç,

File : subnet-win64.exe

If double click on .exe file, I have a warning from windows indicating that the editor is unknown.

Regards,
![Nico](https://user-images.githubusercontent.com/1140708/76004948-a1f94100-5f0a-11ea-97ef-6f08d51b82f1.PNG)

**Comment by midbel** [comment]
subnet is for now only a command line tool! a GUI version (for windows only) is forseen soon. It can only be run from the command line (cmd.exe or any terminal/shell)
